### ISSUE TITLE
Overloaded function decaration for many missing.

### ISSUE THREAD

**Issue by ronaldborman** [keenondrums/types-redux-orm#2]
In index.d.ts around line 202 the 'many' function is declared.

In contrast with the 'fk' and 'oneToOne' function declarations, this function is not overloaded. The version with one required and one optional string parameter is missing.

Is this intentional? AFAICT that version is still part of the redux-orm API.

**Comment by fxlrnrpt** [comment]
@ronaldborman I used JSDoc as reference. https://github.com/tommikaikkonen/redux-orm/blob/master/src/fields.js#L378
They specify there only object as one possible input param.
Though I was able to find overloaded usage in tests.
