### ISSUE TITLE
createReducer

### ISSUE THREAD

**Issue by paulspiteri** [keenondrums/types-redux-orm#3]
I'm just getting to grips with redux-orm so this might be wrong, but are you using the createReducer function? 
Your typing suggests that it doesn't return a reducer (i.e a function), which doesn't appear to be correct.

thanks

**Comment by fxlrnrpt** [comment]
@paulspiteri great catch! Fixed. Yes, I don't use createReducer function. Here's how I suggest to create reducers https://github.com/keenondrums/types-redux-orm#reducer
